<a href="https://colab.research.google.com/github/Anika-34/roc_and_auc_demo/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# introduction to tensors

### creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

scalar.ndim   # scalar has no dimension

In [7]:
# tensor as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape


torch.Size([2, 2])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0][1][1]

tensor(6)

### random tensors

In [27]:
# create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
# random_tensor= torch.rand(1, 3, 4)
random_tensor

tensor([[0.9028, 0.8210, 0.0387, 0.7675],
        [0.6778, 0.8311, 0.2140, 0.8268],
        [0.2133, 0.0055, 0.3371, 0.6639]])

In [31]:
# random tensor with simillar shape to an image tensor
# random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channel
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [34]:
# create a tensor of all zeros
zero =torch.zeros(size=(3, 4))
one = torch.ones(size=(3, 4))
zero, one, one.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [197]:
torch.zeros([2, 4], dtype=torch.int32)
# x = torch.tensor([[1, 2, 3], [4, 5, 6]])
# print(x[1][2])

T = torch.tensor([[1]])
print(T, T.shape)
T.item() # returns a python number

tensor([[1]]) torch.Size([1, 1])


1

### creatign a range of tensors and tensors-like

In [41]:
# torch.range()  -> depricated

# torch.range(1, 10)
one_to_ten = torch.arange(start=1, end =11, step = 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [44]:
# creatin gtensors like
ten_zeros = torch.zeros_like(input =one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### tensor datatypes

In [51]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what data type is tensor
                               device = None, # what device is tensor on
                               requires_grad=False) # wether or not to track gradient with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype  # None dileo float32 ashe

torch.float32

In [52]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [56]:
int_32_tensor=  torch.tensor([3, 6, 9], dtype = torch.int32)
# dtype = torch.int64, torch.long same kaaj kore
int_32_tensor, float_32_tensor* int_32_tensor

(tensor([3, 6, 9], dtype=torch.int32), tensor([ 9., 36., 81.]))

### getting info from tensors
1. `tensor.dtype`
2. `tensor.shape`
3. `tensor.device`

In [57]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9669, 0.5673, 0.3242, 0.4000],
        [0.6258, 0.7299, 0.4972, 0.3148],
        [0.1827, 0.8435, 0.4588, 0.2210]])

In [59]:
print(some_tensor)
print(f"datatype of some tensor: {some_tensor.dtype}")
print(f"shape of some tensor: {some_tensor.shape}, {some_tensor.size()}")
print(f"device: {some_tensor.device}")

tensor([[0.9669, 0.5673, 0.3242, 0.4000],
        [0.6258, 0.7299, 0.4972, 0.3148],
        [0.1827, 0.8435, 0.4588, 0.2210]])
datatype of some tensor: torch.float32
shape of some tensor: torch.Size([3, 4]), torch.Size([3, 4])
device: cpu


### manipulating tensors

Tensor operations
* Addition
* Subtraction
* Multiplication
* division
* matrix multiplication -> "@", matmul, mm

In [83]:
# create a tensor
tensor = torch.tensor([3, 6, 9])
print(tensor + 10)
print(tensor * 10)
print(tensor / 3)
print(tensor - 1)
print(torch.mul(tensor, 10))
print("tensor: ", tensor)

tensor([13, 16, 19])
tensor([30, 60, 90])
tensor([1., 2., 3.])
tensor([2, 5, 8])
tensor([30, 60, 90])
tensor:  tensor([3, 6, 9])


### matrix multiplication

Two main types of multiplication in neural network and deep learning:
1. element wise multiplication
2. matrix multiplication (dot product)

In [85]:
# element wise multiplication

print(tensor, "*", tensor,  "=", tensor* tensor)

tensor([3, 6, 9]) * tensor([3, 6, 9]) = tensor([ 9, 36, 81])


In [92]:
# matrix multiplication
%%time

print(torch.matmul(tensor, tensor))
print(tensor @ tensor)

tensor(126)
tensor(126)
CPU times: user 3.17 ms, sys: 0 ns, total: 3.17 ms
Wall time: 3.18 ms


In [90]:
# by hand

# print(len(tensor))
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(126)
CPU times: user 2.69 ms, sys: 23 µs, total: 2.71 ms
Wall time: 2.54 ms


In [95]:
print(torch.matmul(torch.rand(2, 3), torch.rand(3, 1)))
# print(torch.matmul(torch.rand(2, 3), torch.rand(2, 1))) # this wont work

tensor([[0.3755],
        [0.1917]])


Shape errors

In [100]:
# shapes for mat mul

tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])


# torch.mm(tensor_A, tensor_B) # dimension matcch kore na

print(tensor_A.shape, tensor_B.shape)




torch.Size([3, 2]) torch.Size([3, 2])


to fix this issue use **transpose** ".T"

In [104]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [106]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding min, max, mean, sum, etc...(tensor aggregation)

In [122]:
x = torch.arange(1, 100, 10)
print(x, x.dtype) # int64 is long so mean wont work we have to cast it
print(f"min: {torch.min(x)} or {x.min()}, max: {torch.max(x)} or {x.max()} ")
# print(torch.mean(x)) # datatype error
# RuntimeError: mean(): could not infer output dtype.
# Input dtype must be either a floating point or complex dtype.
# Got: Long

print(torch.mean(x.type(torch.float32)) , "or", x.type(torch.float32).mean())

# sum
print(x.sum())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]) torch.int64
min: 1 or 1, max: 91 or 91 
tensor(46.) or tensor(46.)
tensor(460)


### finding the positional min, max

In [123]:
# find the position in tensor that has the minimum value in tensor with argmin()
print(x.argmin())
print(x[0])


# max
print(x.argmax())
print(x[9])

tensor(0)
tensor(1)
tensor(9)
tensor(91)


### Reshaping, stacking, sqeezing, unsqeezing

* reshaping -> reshapes an input tensor to a defined shape
* View -> Return a view of an input tensorof a certain shape but keep the same memory as the original tensor
* stacking -> combine multiple tensor on top of each other (vstack) or side-by-side (hstack)
* sqeezing -> add a `1` dimension from a tensor
* Unsqeeze -> add a `1` diemnsion to a target tensor
* Permute -> Return a view the input with diemsions permuted in a ertain way

In [157]:
# Create a tensor
import torch
x= torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [158]:
# Add an extra dimesion
# x_reshaped = x.reshape(1, 7) # wont work as tensor size 9 not 7
# x_reshaped = x.reshape(1, 9)
# x_reshaped = x.reshape(2, 9) # because we are trying to double the amount of elemnts without having double the amount of elements
x_reshaped = x.reshape(9, 1)
# python is zero indexed so we add a extra dimension to the first dimension
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [159]:
X = torch.arange(1., 11.)
X, X.size()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [160]:
X_reshaped = X.reshape(2, 5) # this is compatible because 2*5 = 10
X_reshaped, X_reshaped.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

changing `z` changes `x` (because a and z share the same *memory*)

In [161]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [162]:
print(z[:, 3])
z[:, 3] = 0
print(z, x)

tensor([4.])
tensor([[1., 2., 3., 0., 5., 6., 7., 8., 9.]]) tensor([1., 2., 3., 0., 5., 6., 7., 8., 9.])


In [165]:
# Stack tensors on top of each other


# print(x[0])
x_stacked = torch.stack([x, x, x])
print(x_stacked)

x_stacked_2 = torch.stack([x, x, x], dim = 1)
# dim = 1 -> zeroth index is the zeroth tensor ans so on
print(x_stacked_2)

tensor([[1., 2., 3., 0., 5., 6., 7., 8., 9.],
        [1., 2., 3., 0., 5., 6., 7., 8., 9.],
        [1., 2., 3., 0., 5., 6., 7., 8., 9.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [0., 0., 0.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])


```
` torch.squeez(tensor)
```

**squeez** : removes all single dimension from a target **tensor**

In [172]:
# squeez

print(f"x_reshaped: {x_reshaped}, size: {x_reshaped.shape}")
squeezed_x = torch.squeeze(x_reshaped)

print(f"squeezed: {squeezed_x}, size: {squeezed_x.shape}")


x_reshaped: tensor([[1.],
        [2.],
        [3.],
        [0.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]), size: torch.Size([9, 1])
squeezed: tensor([1., 2., 3., 0., 5., 6., 7., 8., 9.]), size: torch.Size([9])


**
```
torch.unsqueez(tensor, dim)
```
**unsqueez**: removes a single dimension to a target tensor at a specific dimension

In [176]:
# unsqueez

print(f"x_reshaped:\n {x_reshaped},\n size: {x_reshaped.shape}")

# unsqueezed_x = torch.unsqueeze(x_reshaped, dim = 0)
unsqueezed_x = torch.unsqueeze(x_reshaped, dim = 1)

print(f"unsqueezed:\n {unsqueezed_x},\n size: {unsqueezed_x.shape}")


x_reshaped:
 tensor([[1.],
        [2.],
        [3.],
        [0.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]),
 size: torch.Size([9, 1])
unsqueezed:
 tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[0.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]]),
 size: torch.Size([9, 1, 1])


```
torch.permute(tensor, dims)
>>> x= torch.randn(2, 3 ,5)
>>> x.size()
# torch.Size([2, 3, 5])
>>> torch.permute(x, (2, 0, 1)).size()
# torch.Size([5, 2, 3])


# the second dimension becomes first, zeroth becomes second, first becomes second
```
* **permute**: rearranges the dimension of a target tensor in a specified order

* permute is in the same memory so changing original also changes the permuted tensor

In [182]:
x_original = torch.rand(size=(5, 4, 3))

x_permuted = x_original.permute(2, 0, 1)  # 3 224 224

print(f"size: {x_original.shape}")
print(f"size: {x_permuted.shape}")

size: torch.Size([5, 4, 3])
size: torch.Size([3, 5, 4])


In [184]:
x_original

tensor([[[0.5614, 0.9994, 0.5567],
         [0.1813, 0.1749, 0.7606],
         [0.5877, 0.0304, 0.6445],
         [0.6472, 0.1246, 0.0339]],

        [[0.2979, 0.2669, 0.1865],
         [0.5829, 0.9185, 0.2534],
         [0.6329, 0.5439, 0.2000],
         [0.1618, 0.9130, 0.1913]],

        [[0.8346, 0.0532, 0.8170],
         [0.8522, 0.8996, 0.5779],
         [0.9029, 0.2250, 0.9957],
         [0.1174, 0.6924, 0.8669]],

        [[0.5750, 0.0350, 0.3175],
         [0.1636, 0.4770, 0.8031],
         [0.8744, 0.1840, 0.6370],
         [0.9747, 0.6833, 0.1749]],

        [[0.5591, 0.2550, 0.0118],
         [0.5452, 0.3866, 0.9713],
         [0.0390, 0.0502, 0.0017],
         [0.5507, 0.9009, 0.6673]]])

In [190]:
x_original[:, :, 0]
x_original[:, 0, 0]
x_original[0, 0, 0] = 0.7869
x_permuted

tensor([[[0.7869, 0.1813, 0.5877, 0.6472],
         [0.2979, 0.5829, 0.6329, 0.1618],
         [0.8346, 0.8522, 0.9029, 0.1174],
         [0.5750, 0.1636, 0.8744, 0.9747],
         [0.5591, 0.5452, 0.0390, 0.5507]],

        [[0.9994, 0.1749, 0.0304, 0.1246],
         [0.2669, 0.9185, 0.5439, 0.9130],
         [0.0532, 0.8996, 0.2250, 0.6924],
         [0.0350, 0.4770, 0.1840, 0.6833],
         [0.2550, 0.3866, 0.0502, 0.9009]],

        [[0.5567, 0.7606, 0.6445, 0.0339],
         [0.1865, 0.2534, 0.2000, 0.1913],
         [0.8170, 0.5779, 0.9957, 0.8669],
         [0.3175, 0.8031, 0.6370, 0.1749],
         [0.0118, 0.9713, 0.0017, 0.6673]]])